### ISSUE TITLE
feat: allow user to override blop sound on first boot volume change

### ISSUE THREAD

**Issue by mikejgray** [OpenVoiceOS/ovos-shell#39]
https://github.com/OpenVoiceOS/ovos-PHAL-plugin-alsa/blob/da06817ddd9d03c0dcf611f05d5fa6fa36cd294f/ovos_PHAL_plugin_alsa/__init__.py#L54

`set_volume()` does have a `play_sound` option but there is no way to set it in the code as it is now

Create a config option, defaulting to true, that allows users to disable the initial blop sound when booting

Per Matrix chat: https://matrix.to/#/!ZhEZYNzKBfpEAhtQIz:matrix.org/$279GVdCG20Gv3dG-3fZ449YGnQlulOyS0g3-eMgpWH8?via=matrix.org&via=nitro.chat&via=strugee.net

**Comment by mikejgray** [comment]
> Although closed, if indeed the NEON update overwrites user config files, that might be a proper bug to report to that update system.
> 
> 
> 
> I believe a system update should not overwrite user config files?

A good callout for sure, and I did reach out to Neon. They confirmed this isn't the case as the settings file is in an XDG path, which isn't changed on update.

**Comment by j1nx** [comment]
> > Although closed, if indeed the NEON update overwrites user config files, that might be a proper bug to report to that update system.
> > I believe a system update should not overwrite user config files?
> 
> A good callout for sure, and I did reach out to Neon. They confirmed this isn't the case as the settings file is in an XDG path, which isn't changed on update.

https://matrix.to/#/!ZhEZYNzKBfpEAhtQIz%3Amatrix.org/%240U7kS0ZCvKwDat6PF1JMK2DUpZgBT41FI_EIEwFZ8Ew 🤦‍♂️🤣
