### ISSUE TITLE
gui menu not available via mouse action on HDMI

### ISSUE THREAD

**Issue by Olzeke51** [OpenVoiceOS/ovos-shell#43]
On a Neon Mark II, sj-201R10, with only an HDMI display, mouse actions do not work on the 'V' pulldown menu event.
The whole screen will move down [so the mouse click is activating an event] but will snap back to the full screen when mouse
[left] button is released.
'
the two side 'event' areas will bring in a different screen {left = big clock}, {right = applications}
iirc - once the menu is displayed [Pi DSI touch screen] the mouse can control/event the different settings
..(was not able to test on the HDMI setup - no external CLI to activate the menu)
.
edit: on a DSI display - the mouse will pull down and open the menu.......

**Comment by JarbasAl** [comment]
seems you are not dragging down further enough

**Comment by Olzeke51** [comment]
tested with a longer/farther pulldown , until the background turned green.
My apologies, the screen size threw me off.
Consider this closed - Gary
